### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by machinexa2** [mayeut/pybase64#212]
In `Python 3.9.1rc1`, pybase64 can be installed and works fine.
In `Python 3.10.0a3+` pybase64 errors out
The Error:
```
  ERROR: Command errored out with exit status 1:
   command: /tmp/cpython/python /usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp5yriidk4
       cwd: /tmp/pip-install-9iqtp0uh/pybase64_2f4e77b175fb49e5b28a8ae23189eae6
  Complete output (141 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/pybase64
  copying pybase64/_fallback.py -> build/lib.linux-x86_64-3.10/pybase64
  copying pybase64Failed to build pybase64
.linux-x86_64-3.10/pybase64
  copying pybase64/_version.py -> build/lib.linux-x86_64-3.10/pybase64
  copying pybase64/__main__.py -> build/lib.linux-x86_64-3.10/pybase64
  copying pybase64/_license.py -> build/lib.linux-x86_64-3.10/pybase64
  creating build/lib.linux-x86_64-3.10/pybase64/tests
  copying pybase64/tests/__init__.py -> build/lib.linux-x86_64-3.10/pybase64/tests
  copying pybase64/tests/test_main.py -> build/lib.linux-x86_64-3.10/pybase64/tests
  copying pybase64/tests/test_pybase64.py -> build/lib.linux-x86_64-3.10/pybase64/tests
  creating build/lib.linux-x86_64-3.10/pybase64/distutils
  copying pybase64/distutils/__init__.py -> build/lib.linux-x86_64-3.10/pybase64/distutils
  copying pybase64/distutils/ccompilercapabilities.py -> build/lib.linux-x86_64-3.10/pybase64/distutils
  running build_ext
  building 'pybase64._pybase64' extension
  getting compiler simd support
  SSSE3: True
  SSE41: True
  SSE42: True
  AVX:   True
  AVX2:  True
  NEON32:  False
  creating 'base64/lib/config.h'
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/base64
  creating build/temp.linux-x86_64-3.10/base64/lib
  creating build/temp.linux-x86_64-3.10/base64/lib/arch
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/ssse3
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/ssse3/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/ssse3/codec.o -mssse3 -D__SSSE3__
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/sse41
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/sse41/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/sse41/codec.o -msse4.1 -D__SSE4_1__
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/sse42
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/sse42/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/sse42/codec.o -msse4.2 -D__SSE4_2__
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/avx
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/avx/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/avx/codec.o -mavx -D__AVX__
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/avx2
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/avx2/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/avx2/codec.o -mavx2 -D__AVX2__
  creating build/temp.linux-x86_64-3.10/pybase64
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/generic
  creating build/temp.linux-x86_64-3.10/base64/lib/tables
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/neon32
  creating build/temp.linux-x86_64-3.10/base64/lib/arch/neon64
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c pybase64/_pybase64.c -o build/temp.linux-x86_64-3.10/pybase64/_pybase64.o
  pybase64/_pybase64.c: In function ‘pybase64_encode_impl’:
  pybase64/_pybase64.c:303:57: warning: passing argument 4 of ‘_PyArg_ParseTupleAndKeywords_SizeT’ from incompatible pointer type [-Wincompatible-pointer-types]
    303 |     if (!PyArg_ParseTupleAndKeywords(args, kwds, "O|O", kwlist, &in_object, &in_alphabet)) {
        |                                                         ^~~~~~
        |                                                         |
        |                                                         const char **
  In file included from /tmp/cpython/Include/Python.h:141,
                   from pybase64/_pybase64.c:3:
  /tmp/cpython/Include/modsupport.h:42:65: note: expected ‘char **’ but argument is of type ‘const char **’
     42 |                                                   const char *, char **, ...);
        |                                                                 ^~~~~~~
  pybase64/_pybase64.c: In function ‘pybase64_decode_impl’:
  pybase64/_pybase64.c:397:58: warning: passing argument 4 of ‘_PyArg_ParseTupleAndKeywords_SizeT’ from incompatible pointer type [-Wincompatible-pointer-types]
    397 |     if (!PyArg_ParseTupleAndKeywords(args, kwds, "O|Ob", kwlist, &in_object, &in_alphabet, &validation)) {
        |                                                          ^~~~~~
        |                                                          |
        |                                                          const char **
  In file included from /tmp/cpython/Include/Python.h:141,
                   from pybase64/_pybase64.c:3:
  /tmp/cpython/Include/modsupport.h:42:65: note: expected ‘char **’ but argument is of type ‘const char **’
     42 |                                                   const char *, char **, ...);
        |                                                                 ^~~~~~~
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c pybase64/_pybase64_get_simd_flags.c -o build/temp.linux-x86_64-3.10/pybase64/_pybase64_get_simd_flags.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/lib.c -o build/temp.linux-x86_64-3.10/base64/lib/lib.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/codec_choose.c -o build/temp.linux-x86_64-3.10/base64/lib/codec_choose.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/generic/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/generic/codec.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/tables/tables.c -o build/temp.linux-x86_64-3.10/base64/lib/tables/tables.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/neon32/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/neon32/codec.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ibase64/include/ -Ibase64/lib/ -I/tmp/cpython/Include -I/tmp/cpython -c base64/lib/arch/neon64/codec.c -o build/temp.linux-x86_64-3.10/base64/lib/arch/neon64/codec.o
  gcc -pthread -shared build/temp.linux-x86_64-3.10/base64/lib/arch/ssse3/codec.o build/temp.linux-x86_64-3.10/base64/lib/arch/sse41/codec.o build/temp.linux-x86_64-3.10/base64/lib/arch/sse42/codec.o build/temp.linux-x86_64-3.10/base64/lib/arch/avx/codec.o build/temp.linux-x86_64-3.10/base64/lib/arch/avx2/codec.o build/temp.linux-x86_64-3.10/pybase64/_pybase64.o build/temp.linux-x86_64-3.10/pybase64/_pybase64_get_simd_flags.o build/temp.linux-x86_64-3.10/base64/lib/lib.o build/temp.linux-x86_64-3.10/base64/lib/codec_choose.o build/temp.linux-x86_64-3.10/base64/lib/arch/generic/codec.o build/temp.linux-x86_64-3.10/base64/lib/tables/tables.o build/temp.linux-x86_64-3.10/base64/lib/arch/neon32/codec.o build/temp.linux-x86_64-3.10/base64/lib/arch/neon64/codec.o -o build/lib.linux-x86_64-3.10/pybase64/_pybase64.cpython-310-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/pybase64
  copying build/lib.linux-x86_64-3.10/pybase64/_fallback.py -> build/bdist.linux-x86_64/wheel/pybase64
  copying build/lib.linux-x86_64-3.10/pybase64/_pybase64.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/pybase64
  copying build/lib.linux-x86_64-3.10/pybase64/__init__.py -> build/bdist.linux-x86_64/wheel/pybase64
  creating build/bdist.linux-x86_64/wheel/pybase64/tests
  copying build/lib.linux-x86_64-3.10/pybase64/tests/__init__.py -> build/bdist.linux-x86_64/wheel/pybase64/tests
  copying build/lib.linux-x86_64-3.10/pybase64/tests/test_main.py -> build/bdist.linux-x86_64/wheel/pybase64/tests
  copying build/lib.linux-x86_64-3.10/pybase64/tests/test_pybase64.py -> build/bdist.linux-x86_64/wheel/pybase64/tests
  copying build/lib.linux-x86_64-3.10/pybase64/_version.py -> build/bdist.linux-x86_64/wheel/pybase64
  copying build/lib.linux-x86_64-3.10/pybase64/__main__.py -> build/bdist.linux-x86_64/wheel/pybase64
  creating build/bdist.linux-x86_64/wheel/pybase64/distutils
  copying build/lib.linux-x86_64-3.10/pybase64/distutils/__init__.py -> build/bdist.linux-x86_64/wheel/pybase64/distutils
  copying build/lib.linux-x86_64-3.10/pybase64/distutils/ccompilercapabilities.py -> build/bdist.linux-x86_64/wheel/pybase64/distutils
  copying build/lib.linux-x86_64-3.10/pybase64/_license.py -> build/bdist.linux-x86_64/wheel/pybase64
  running install_egg_info
  running egg_info
  writing pybase64.egg-info/PKG-INFO
  writing dependency_links to pybase64.egg-info/dependency_links.txt
  writing entry points to pybase64.egg-info/entry_points.txt
  writing requirements to pybase64.egg-info/requires.txt
  writing top-level names to pybase64.egg-info/top_level.txt
  reading manifest file 'pybase64.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'base64/.git'
  warning: no previously-included files matching '.*' found anywhere in distribution
  writing manifest file 'pybase64.egg-info/SOURCES.txt'
  Copying pybase64.egg-info to build/bdist.linux-x86_64/wheel/pybase64-1.1.1-py3.10.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 207, in <module>
      setup(
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/cpython/Lib/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/tmp/cpython/Lib/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/tmp/cpython/Lib/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 337, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/tmp/pip-build-env-nel_s6w2/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 287, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for pybase64
ERROR: Could not build wheels for pybase64 which use PEP 517 and cannot be installed directly
```
The problem could either be in python3.10 or your code. I am not sure
Reproducing:
```bash
git clone https://github.com/python/cpython/
cd cpython
./configure --enable-optimizations 
make
./python -m pip install pybase64
```

**Comment by mayeut** [comment]
@machinexa2, thanks for the report. It's a known issue of wheel/python3.10 : pypa/wheel#354

**Comment by machinexa2** [comment]
@mayeut nvm, I will stop using python3.10 for now, I hope it gets fixed in future versions.
